### ISSUE TITLE
On desktop the search of the current position does not work as expected

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-mentor-otp#116]
https://user-images.githubusercontent.com/9825179/144925411-a222fd3a-5d9a-42e2-8041-dec7ad624ee4.mp4

**Comment by zabuTNT** [comment]
It works to me, in our office (the provider is TIM Business), but could be a coincidence, because the cabinet is near the office.
![2021-12-10-090320_1330x732_scrot](https://user-images.githubusercontent.com/5268372/145538995-a73f400f-1965-4208-9ace-092310cdee7b.png)
On desktop the position is related and provided by ISP provider, so could be or not to be near you real position.

**Comment by rcavaliere** [comment]
OK
